[settings]
# whether to prompt to install plugins and runtimes if they're not already installed
# missing_runtime_behavior = 'warn' # other options: 'ignore', 'warn', 'prompt', 'autoinstall'

# verbose = false     # set to true to see full installation output, see `RTX_VERBOSE`
# asdf_compat = false # set to true to ensure .tool-versions will be compatible with asdf, see `RTX_ASDF_COMPAT`
# jobs = 4            # number of plugins or runtimes to install in parallel. The default is `4`.
# raw = false         # set to true to directly pipe plugins to stdin/stdout/stderr

experimental = true                    # enable experimental features such as shims and core plugins
disable_hints = ["python_precompiled"]
python_compile = false
idiomatic_version_file_enable_tools = ["terraform", "opentofu", "go", "node", "java"]

# Aliases make install/update easier. Instead of `mise up `github:rvben/rumdl`, you can do `mise up rumdl`.
[tool_alias]
# awscli from Aqua is weird, use asdf plugin
awscli = "asdf:https://github.com/MetricMike/asdf-awscli.git"
beads = "github:steveyegge/beads"
hub = "go:github.com/mislav/hub"
moon = "github:moonrepo/moon"
opencode = "aqua:anomalyco/opencode"
pipx = "pipx:vectorcode"
procs = "github:dalance/procs"
rumdl = "github:rvben/rumdl"
whoAMI-scanner = "github:DataDog/whoAMI-scanner"
pup = "github:DataDog/pup"
vibe = "github:lynaghk/vibe"

[tools]
argo = "4"
argocd = "3"
awscli = "2"
beads = "latest"
bitwarden = "cli-v2025"
chezmoi = "2"
cloudflared = "2026"
conftest = "0"
difftastic = "latest"
direnv = "2"
dive = "0"
golang = "1"
golangci-lint = "2"
gradle = "9"
granted = "0"
grpcurl = "1"
helm = "4"
helm-docs = "1"
hey = "0"
iam-policy-json-to-terraform = "1"
java = "corretto-25"
jq = "1"
k9s = "0"
kind = "0"
krew = "0"
kubectl = "1"
kubent = "0"
lua = "5.1" # pinned to 5.1 for nvim compatability
neovim = "nightly" #"latest"
nodejs = "25"
python = "3.14"
ruby = "4"
shellcheck = "0"
sops = "3"
sopstool = "1"
steampipe = "2"
stern = "1"
terraform = "1"
terraform-docs = "0"
terraform-validator = "3"
tflint = "0"
tfsec = "1"
tonnage = "0"
usage = "2"
viddy = "1"
yq = "4"
rust = "latest"
powerpipe = "latest"
eza = "latest"
bat = "latest"
fd = "latest"
fzf = "latest"
grex = "latest"
delta = "latest"
glow = "latest"
ripgrep = "latest"
gh = "latest"
editorconfig-checker = "latest"
actionlint = "latest"
tree-sitter = "latest"
cargo-binstall = "latest"
cargo = "latest"
# "github:aws/amazon-ec2-instance-selector" = "latest"
uv = "latest"
cosign = "3"
syft = "latest"
rumdl = "latest"
procs = "latest"
whoAMI-scanner = "latest"
hub = "v2" # using go because it gets me an aarm64 binary, all other methods get x86_64
pipx = "latest"
opencode = "latest"
moon = "latest"
crane = "latest"
ubi = "latest"
tmux = "latest"
bun = "latest"
vibe = "latest"
pup = "latest"
